import { db } from "./index";
import { species } from "./schema";

const SEED: (typeof species.$inferInsert)[] = [
  // 已存在的不会重复（onConflictDoNothing），按 commonName 自然合并
  {
    commonName: "绿萝",
    scientificName: "Epipremnum aureum",
    family: "天南星科",
    category: "观叶",
    careLight: "散光，避免直射",
    careWater: "土干透浇透，约 5-10 天 / 次",
    careTemp: "15-28°C",
    careHumidity: "中高湿度，可叶面喷雾",
    careNotes: "极易繁殖，剪枝水插即可生根。",
  },
  {
    commonName: "多肉·桃蛋",
    scientificName: "Graptopetalum amethystinum",
    family: "景天科",
    category: "多肉",
    careLight: "全日照，弱光易徒长",
    careWater: "干透浇透，秋冬控水",
    careTemp: "5-30°C，怕高温闷",
    careHumidity: "低，需通风",
    careNotes: "夏季避免暴晒+雨淋；冷凉季节出粉上色。",
  },
  {
    commonName: "龟背竹",
    scientificName: "Monstera deliciosa",
    family: "天南星科",
    category: "观叶",
    careLight: "明亮散光",
    careWater: "表土干 2-3cm 再浇，约 7 天 / 次",
    careTemp: "18-30°C",
    careHumidity: "中高湿度，叶面喷雾或加湿器",
    careNotes: "立柱可促叶片开裂；春夏施肥 2-4 周一次。",
  },
  // ↓ 用户补充列表
  {
    commonName: "秋海棠",
    scientificName: "Begonia spp.",
    family: "秋海棠科",
    category: "观叶/观花",
    careLight: "明亮散光，避免烈日",
    careWater: "表土微干就浇，约 4-7 天",
    careTemp: "15-25°C",
    careHumidity: "高湿，怕闷",
    careNotes: "夏季避高温闷热；叶面少喷水易烂。",
  },
  {
    commonName: "矮牵牛",
    scientificName: "Petunia × hybrida",
    family: "茄科",
    category: "一年生草本",
    careLight: "全日照",
    careWater: "盆土发白再浇，约 2-3 天，花期更勤",
    careTemp: "15-28°C",
    careHumidity: "中等",
    careNotes: "花后摘残花，控顶可塑花球；忌淋雨。",
  },
  {
    commonName: "蓝目菊",
    scientificName: "Osteospermum spp.",
    family: "菊科",
    category: "多年生草花",
    careLight: "全日照",
    careWater: "干透浇透，约 3-5 天",
    careTemp: "10-25°C，耐寒不耐酷暑",
    careHumidity: "低-中",
    careNotes: "夏季高温会假死，秋凉恢复；勤摘残花。",
  },
  {
    commonName: "卷叶榕",
    scientificName: "Ficus benjamina 'Curly'",
    family: "桑科",
    category: "木本观叶",
    careLight: "明亮散光",
    careWater: "表土干就浇，约 5-7 天",
    careTemp: "15-28°C",
    careHumidity: "中高",
    careNotes: "怕频繁挪动，换位置后掉叶属正常。",
  },
  {
    commonName: "鸭脚木",
    scientificName: "Heptapleurum arboricola",
    family: "五加科",
    category: "木本观叶",
    careLight: "散光至半阴",
    careWater: "干透浇透，约 7-10 天",
    careTemp: "10-28°C",
    careHumidity: "中",
    careNotes: "净化空气强，养护省心，怕积水。",
  },
  {
    commonName: "飞机蔓绿绒",
    scientificName: "Philodendron 'Florida Beauty'",
    family: "天南星科",
    category: "观叶",
    careLight: "明亮散光",
    careWater: "表土干 2cm 再浇，约 5-7 天",
    careTemp: "18-28°C",
    careHumidity: "中高，多喷雾",
    careNotes: "立柱可促长大叶；气根别剪。",
  },
  {
    commonName: "迷岩",
    scientificName: "Petrocosmea spp.",
    family: "苦苣苔科",
    category: "苦苣苔",
    careLight: "明亮散光，避免直射",
    careWater: "表土微干浇水，避免叶面",
    careTemp: "15-25°C",
    careHumidity: "中高",
    careNotes: "莲座状叶片对生；忌闷热，喜稳定湿度，浸盆更安全。",
  },
  {
    commonName: "迷套",
    scientificName: "Primulina spp.",
    family: "苦苣苔科",
    category: "苦苣苔",
    careLight: "明亮散光",
    careWater: "表土微干浇水，浸盆更稳",
    careTemp: "15-25°C",
    careHumidity: "中高",
    careNotes: "喜稳湿不喜叶面水；夏季多通风防化水。",
  },
  {
    commonName: "花猫",
    scientificName: "Primulina 'Hua Mao'",
    family: "苦苣苔科",
    category: "苦苣苔",
    careLight: "明亮散光",
    careWater: "表土微干浇水，避免叶面",
    careTemp: "15-25°C",
    careHumidity: "中高",
    careNotes: "锦化苦苣苔，光照足时叶纹更清晰；忌烈日。",
  },
  {
    commonName: "大岩桐",
    scientificName: "Sinningia speciosa",
    family: "苦苣苔科",
    category: "球根",
    careLight: "明亮散光",
    careWater: "表土微干浇水，避免叶面",
    careTemp: "18-25°C",
    careHumidity: "中高",
    careNotes: "花后块茎休眠，冬季可断水保块茎。",
  },
  {
    commonName: "堇兰",
    scientificName: "Saintpaulia ionantha",
    family: "苦苣苔科",
    category: "苦苣苔",
    careLight: "明亮散光",
    careWater: "浸盆为主，叶面忌沾水",
    careTemp: "18-25°C",
    careHumidity: "中高",
    careNotes: "即非洲堇；叶面留水会出黄斑；用温水浸盆 20 分钟。",
  },
  {
    commonName: "皮草花",
    scientificName: "Episcia cupreata",
    family: "苦苣苔科",
    category: "观叶/观花",
    careLight: "明亮散光",
    careWater: "表土微干就浇",
    careTemp: "18-28°C",
    careHumidity: "高",
    careNotes: "叶子绒毛，怕碰水；用浸盆法。",
  },
  {
    commonName: "文心兰",
    scientificName: "Oncidium spp.",
    family: "兰科",
    category: "兰花",
    careLight: "明亮散光",
    careWater: "假鳞茎微皱再浇",
    careTemp: "15-28°C",
    careHumidity: "中高",
    careNotes: "花后剪掉花梗保留假鳞茎；周年可发芽。",
  },
  {
    commonName: "迷迭香",
    scientificName: "Salvia rosmarinus",
    family: "唇形科",
    category: "香草",
    careLight: "全日照",
    careWater: "干透浇透，怕涝",
    careTemp: "5-30°C",
    careHumidity: "低",
    careNotes: "耐旱不耐湿；多通风，少氮肥。",
  },
  {
    commonName: "薄荷",
    scientificName: "Mentha spp.",
    family: "唇形科",
    category: "香草",
    careLight: "全日照至半阴",
    careWater: "表土发干就浇，约 2-3 天",
    careTemp: "10-28°C",
    careHumidity: "中",
    careNotes: "生命力强，繁殖快；建议单独一盆防「抢地盘」。",
  },
  {
    commonName: "长寿花",
    scientificName: "Kalanchoe blossfeldiana",
    family: "景天科",
    category: "多肉/观花",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "10-25°C",
    careHumidity: "低",
    careNotes: "短日照诱导花芽（每天 < 10h 光照 6-8 周）。",
  },
  {
    commonName: "百万小铃",
    scientificName: "Calibrachoa spp.",
    family: "茄科",
    category: "草花",
    careLight: "全日照",
    careWater: "表土干就浇，花期勤浇",
    careTemp: "10-28°C",
    careHumidity: "中",
    careNotes: "花后摘残花促复花；夏季避烈日。",
  },
  {
    commonName: "百日草",
    scientificName: "Zinnia elegans",
    family: "菊科",
    category: "一年生草花",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "15-30°C",
    careHumidity: "中",
    careNotes: "极易播种，30 天发芽到开花约 60 天。",
  },
  {
    commonName: "翠芦莉",
    scientificName: "Ruellia simplex",
    family: "爵床科",
    category: "草花",
    careLight: "全日照",
    careWater: "盆土微干就浇",
    careTemp: "15-30°C",
    careHumidity: "中高",
    careNotes: "一日花，每天开新花；可粗放养护。",
  },
  {
    commonName: "紫叶酢浆草",
    scientificName: "Oxalis triangularis",
    family: "酢浆草科",
    category: "球根",
    careLight: "散光",
    careWater: "盆土微干浇水",
    careTemp: "15-25°C",
    careHumidity: "中",
    careNotes: "夜间叶子合拢；夏季会暂时休眠。",
  },
  {
    commonName: "虎刺梅",
    scientificName: "Euphorbia milii",
    family: "大戟科",
    category: "多肉/观花",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "15-30°C",
    careHumidity: "低",
    careNotes: "汁液有毒勿入眼；浇水耐寒不如耐旱。",
  },
  {
    commonName: "绣球花",
    scientificName: "Hydrangea macrophylla",
    family: "绣球科",
    category: "灌木/观花",
    careLight: "明亮散光至半阴",
    careWater: "盆土稍干就浇，花期大水",
    careTemp: "10-25°C",
    careHumidity: "中高",
    careNotes: "土壤 pH 影响花色：酸蓝碱粉。冬季注意修剪老枝。",
  },
  {
    commonName: "龙鳞春雨",
    scientificName: "Philodendron 'Dragon Scale'",
    family: "天南星科",
    category: "观叶",
    careLight: "明亮散光",
    careWater: "表土干 2cm 再浇",
    careTemp: "18-28°C",
    careHumidity: "高",
    careNotes: "叶面有龙鳞质感，喜湿；立柱可长更大叶。",
  },
  {
    commonName: "野路菊",
    scientificName: "Rhodanthemum hosmariense",
    family: "菊科",
    category: "多年生草花",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "5-25°C",
    careHumidity: "低",
    careNotes: "耐寒小菊；花期长，避免淋雨烂根。",
  },
  {
    commonName: "纸鳞托菊",
    scientificName: "Rhodanthe spp.",
    family: "菊科",
    category: "一年生草花",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "10-25°C",
    careHumidity: "低",
    careNotes: "纸质花瓣，干燥后亦能做干花。",
  },
  {
    commonName: "摩洛哥雏菊",
    scientificName: "Rhodanthemum hosmariense 'Casablanca'",
    family: "菊科",
    category: "多年生草花",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "5-25°C",
    careHumidity: "低",
    careNotes: "灰绿叶+白瓣黄心；忌闷湿。",
  },
  {
    commonName: "铁线莲",
    scientificName: "Clematis spp.",
    family: "毛茛科",
    category: "攀援藤本",
    careLight: "上部全日照，根部阴凉",
    careWater: "盆土稍干就浇",
    careTemp: "5-28°C",
    careHumidity: "中",
    careNotes: "三大修剪组：第一组只剪枯，二组花后轻剪，三组重剪；上盆给棚架。",
  },
  {
    commonName: "旱金莲",
    scientificName: "Tropaeolum majus",
    family: "旱金莲科",
    category: "草花/食用",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "10-28°C",
    careHumidity: "中",
    careNotes: "花和叶可食用，味微辣；不喜大水大肥。",
  },
  {
    commonName: "美女樱",
    scientificName: "Verbena × hybrida",
    family: "马鞭草科",
    category: "草花",
    careLight: "全日照",
    careWater: "盆土微干就浇",
    careTemp: "10-28°C",
    careHumidity: "中",
    careNotes: "丰花连续开，花后剪一刀促复花。",
  },
  {
    commonName: "露薇花",
    scientificName: "Lewisia cotyledon",
    family: "马齿苋科",
    category: "多年生草花",
    careLight: "散光至明亮",
    careWater: "干透浇透，怕涝",
    careTemp: "5-22°C",
    careHumidity: "低",
    careNotes: "原产高山，要求排水极佳；铺面石防领口烂。",
  },
  {
    commonName: "玲珑菊",
    scientificName: "Argyranthemum frutescens",
    family: "菊科",
    category: "灌木状草花",
    careLight: "全日照",
    careWater: "盆土微干就浇",
    careTemp: "5-25°C",
    careHumidity: "中",
    careNotes: "可塑棒棒糖造型；夏季避酷暑。",
  },

  // === 第二批扩充 ===
  // —— 观叶 ——
  {
    commonName: "散尾葵",
    scientificName: "Dypsis lutescens",
    family: "棕榈科",
    category: "木本观叶",
    careLight: "明亮散光",
    careWater: "表土干 1-2cm 再浇，约 5-7 天",
    careTemp: "18-28°C",
    careHumidity: "中高",
    careNotes: "怕积水更怕干透；叶尖发黄多因干燥+缺水。",
  },
  {
    commonName: "龙血树",
    scientificName: "Dracaena fragrans",
    family: "天门冬科",
    category: "木本观叶",
    careLight: "明亮散光至半阴",
    careWater: "干透浇透，约 7-14 天",
    careTemp: "15-28°C",
    careHumidity: "中",
    careNotes: "省心好养；怕氟水，建议晾水或用过滤水。",
  },
  {
    commonName: "橡皮树",
    scientificName: "Ficus elastica",
    family: "桑科",
    category: "木本观叶",
    careLight: "明亮散光",
    careWater: "干透浇透，约 7 天",
    careTemp: "15-30°C",
    careHumidity: "中",
    careNotes: "汁液会污渍衣物；可剪顶促分枝。",
  },
  {
    commonName: "琴叶榕",
    scientificName: "Ficus lyrata",
    family: "桑科",
    category: "木本观叶",
    careLight: "明亮散光，缺光会掉叶",
    careWater: "干透浇透，约 7-10 天",
    careTemp: "15-28°C",
    careHumidity: "中",
    careNotes: "怕挪动；位置定好后尽量不搬。",
  },
  {
    commonName: "富贵竹",
    scientificName: "Dracaena sanderiana",
    family: "天门冬科",
    category: "观叶",
    careLight: "散光至半阴",
    careWater: "水培或盆栽；水培每周换水",
    careTemp: "15-28°C",
    careHumidity: "中",
    careNotes: "水培加几滴营养液；怕氯，用晾置水。",
  },
  {
    commonName: "万年青",
    scientificName: "Aglaonema spp.",
    family: "天南星科",
    category: "观叶",
    careLight: "散光",
    careWater: "表土干就浇，约 5-7 天",
    careTemp: "15-28°C",
    careHumidity: "中高",
    careNotes: "耐阴，怕冷，冬季 < 12°C 易冻伤。",
  },
  {
    commonName: "镜面草",
    scientificName: "Pilea peperomioides",
    family: "荨麻科",
    category: "观叶",
    careLight: "明亮散光",
    careWater: "表土干就浇，约 5-7 天",
    careTemp: "13-25°C",
    careHumidity: "中",
    careNotes: "易爆侧芽分株繁殖；缺光叶子会上仰过密。",
  },

  // —— 多肉 ——
  {
    commonName: "玉露",
    scientificName: "Haworthia obtusa",
    family: "阿福花科",
    category: "多肉",
    careLight: "明亮散光，避免烈日",
    careWater: "干透浇透，秋冬控水",
    careTemp: "5-28°C",
    careHumidity: "低-中",
    careNotes: "透明窗状叶；暴晒会窗面变红失透。",
  },
  {
    commonName: "玉扇",
    scientificName: "Haworthia truncata",
    family: "阿福花科",
    category: "多肉",
    careLight: "明亮散光",
    careWater: "干透浇透",
    careTemp: "5-28°C",
    careHumidity: "低-中",
    careNotes: "扁平窗状叶呈扇形；夏季短暂半休眠。",
  },
  {
    commonName: "黑王子",
    scientificName: "Echeveria 'Black Prince'",
    family: "景天科",
    category: "多肉",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "5-28°C",
    careHumidity: "低",
    careNotes: "光照足时叶色越深黑紫；夏季避暴雨。",
  },
  {
    commonName: "火祭",
    scientificName: "Crassula capitella 'Campfire'",
    family: "景天科",
    category: "多肉",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "5-30°C",
    careHumidity: "低",
    careNotes: "全日照 + 温差变红；夏季避高温闷。",
  },
  {
    commonName: "虹之玉",
    scientificName: "Sedum rubrotinctum",
    family: "景天科",
    category: "多肉",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "5-30°C",
    careHumidity: "低",
    careNotes: "易叶插繁殖；光足时叶尖变红如糖果。",
  },
  {
    commonName: "黄丽",
    scientificName: "Sedum adolphi",
    family: "景天科",
    category: "多肉",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "5-30°C",
    careHumidity: "低",
    careNotes: "光照足时叶呈金黄色，缺光变绿。",
  },
  {
    commonName: "山地玫瑰",
    scientificName: "Aeonium aureum",
    family: "景天科",
    category: "多肉",
    careLight: "明亮散光至全日照",
    careWater: "干透浇透，夏季严控",
    careTemp: "5-22°C，惧酷暑",
    careHumidity: "低",
    careNotes: "夏季紧抱成「玫瑰球」休眠，秋凉重新展开。",
  },
  {
    commonName: "生石花",
    scientificName: "Lithops spp.",
    family: "番杏科",
    category: "多肉",
    careLight: "全日照",
    careWater: "严控水；蜕皮期完全断水",
    careTemp: "5-30°C",
    careHumidity: "极低",
    careNotes: "一年一次蜕皮（春），新植株从旧体内长出；浇水过多必裂。",
  },

  // —— 苦苣苔类（已有 6 种） ——
  {
    commonName: "海豚花",
    scientificName: "Streptocarpus saxorum",
    family: "苦苣苔科",
    category: "苦苣苔",
    careLight: "明亮散光",
    careWater: "表土微干浇水，浸盆更稳",
    careTemp: "15-25°C",
    careHumidity: "中高",
    careNotes: "花形似小海豚；忌叶面湿。",
  },
  {
    commonName: "口红花",
    scientificName: "Aeschynanthus radicans",
    family: "苦苣苔科",
    category: "苦苣苔/附生",
    careLight: "明亮散光",
    careWater: "表土微干就浇",
    careTemp: "18-28°C",
    careHumidity: "高",
    careNotes: "附生攀援；红色管状花像口红挤出。",
  },

  // —— 兰花 ——
  {
    commonName: "蝴蝶兰",
    scientificName: "Phalaenopsis spp.",
    family: "兰科",
    category: "兰花/附生",
    careLight: "明亮散光",
    careWater: "介质微干浇透，约 7-10 天",
    careTemp: "18-28°C",
    careHumidity: "中高",
    careNotes: "花后剪到花梗 2-3 节有可能复花；空气湿润 + 流通。",
  },
  {
    commonName: "石斛兰",
    scientificName: "Dendrobium spp.",
    family: "兰科",
    category: "兰花/附生",
    careLight: "明亮散光至全日",
    careWater: "干湿交替明显，冬季少水",
    careTemp: "10-28°C",
    careHumidity: "中高",
    careNotes: "假鳞茎储水；冬季干燥+低温有利花芽。",
  },
  {
    commonName: "卡特兰",
    scientificName: "Cattleya spp.",
    family: "兰科",
    category: "兰花/附生",
    careLight: "明亮散光至轻度直射",
    careWater: "假鳞茎微皱再浇",
    careTemp: "15-30°C",
    careHumidity: "中高",
    careNotes: "光足才会开花；春夏施肥，冬季控水。",
  },

  // —— 球根/秋植 ——
  {
    commonName: "风信子",
    scientificName: "Hyacinthus orientalis",
    family: "天门冬科",
    category: "球根",
    careLight: "明亮散光至全日",
    careWater: "盆栽干透浇透；水培每周换水",
    careTemp: "5-15°C 促花",
    careHumidity: "中",
    careNotes: "需 8-10 周低温春化才会开花。",
  },
  {
    commonName: "郁金香",
    scientificName: "Tulipa spp.",
    family: "百合科",
    category: "球根",
    careLight: "全日照",
    careWater: "盆土微干就浇",
    careTemp: "5-18°C",
    careHumidity: "中",
    careNotes: "秋植春开，需冷凉春化；多数为一次性球。",
  },
  {
    commonName: "水仙",
    scientificName: "Narcissus spp.",
    family: "石蒜科",
    category: "球根",
    careLight: "全日照",
    careWater: "土培或水养均可",
    careTemp: "5-18°C",
    careHumidity: "中",
    careNotes: "中国水仙水养简单；漳州水仙最佳，开后球可弃。",
  },
  {
    commonName: "朱顶红",
    scientificName: "Hippeastrum spp.",
    family: "石蒜科",
    category: "球根",
    careLight: "明亮散光",
    careWater: "干透浇透；冬季可断水休眠",
    careTemp: "15-28°C",
    careHumidity: "中",
    careNotes: "球露土 1/3 种；花后留叶养球，明年再开。",
  },
  {
    commonName: "番红花",
    scientificName: "Crocus spp.",
    family: "鸢尾科",
    category: "球根",
    careLight: "全日照",
    careWater: "盆土干就浇",
    careTemp: "5-18°C",
    careHumidity: "中",
    careNotes: "秋种冬春开；柱头即藏红花香料原料。",
  },

  // —— 香草 ——
  {
    commonName: "罗勒",
    scientificName: "Ocimum basilicum",
    family: "唇形科",
    category: "香草/一年生",
    careLight: "全日照",
    careWater: "盆土稍干就浇，喜水",
    careTemp: "18-30°C",
    careHumidity: "中",
    careNotes: "怕冷一年生；摘心多枝，开花前最香。",
  },
  {
    commonName: "百里香",
    scientificName: "Thymus vulgaris",
    family: "唇形科",
    category: "香草",
    careLight: "全日照",
    careWater: "干透浇透，耐旱",
    careTemp: "5-30°C",
    careHumidity: "低",
    careNotes: "怕涝；矮丛灌木型，常年可剪叶用。",
  },
  {
    commonName: "鼠尾草",
    scientificName: "Salvia officinalis",
    family: "唇形科",
    category: "香草",
    careLight: "全日照",
    careWater: "干透浇透，耐旱",
    careTemp: "5-30°C",
    careHumidity: "低",
    careNotes: "灰绿叶有独特香气；料理常配肉类。",
  },
  {
    commonName: "香茅",
    scientificName: "Cymbopogon citratus",
    family: "禾本科",
    category: "香草",
    careLight: "全日照",
    careWater: "喜水，常保湿润",
    careTemp: "18-30°C",
    careHumidity: "中高",
    careNotes: "丛生草本；茎部用作泰式料理 + 防蚊。",
  },

  // —— 蕨类 ——
  {
    commonName: "鸟巢蕨",
    scientificName: "Asplenium nidus",
    family: "铁角蕨科",
    category: "蕨类",
    careLight: "散光至半阴",
    careWater: "表土微干就浇，喜湿",
    careTemp: "18-28°C",
    careHumidity: "高",
    careNotes: "中心巢状切勿积水；高湿度叶面亮绿。",
  },
  {
    commonName: "肾蕨",
    scientificName: "Nephrolepis cordifolia",
    family: "肾蕨科",
    category: "蕨类",
    careLight: "散光",
    careWater: "保持湿润，不耐干",
    careTemp: "15-28°C",
    careHumidity: "中高",
    careNotes: "干燥即落叶；常配高湿环境。",
  },
  {
    commonName: "波士顿蕨",
    scientificName: "Nephrolepis exaltata 'Bostoniensis'",
    family: "肾蕨科",
    category: "蕨类",
    careLight: "散光",
    careWater: "保持湿润",
    careTemp: "15-28°C",
    careHumidity: "高",
    careNotes: "经典悬挂蕨；干燥环境频繁掉叶。",
  },
  {
    commonName: "铁线蕨",
    scientificName: "Adiantum capillus-veneris",
    family: "凤尾蕨科",
    category: "蕨类",
    careLight: "散光至半阴",
    careWater: "始终湿润，绝不干透",
    careTemp: "15-25°C",
    careHumidity: "高",
    careNotes: "出名「娇气」；常用浸盆 + 加湿器。",
  },

  // —— 食虫 ——
  {
    commonName: "捕蝇草",
    scientificName: "Dionaea muscipula",
    family: "茅膏菜科",
    category: "食虫",
    careLight: "全日照 6 小时+",
    careWater: "纯水/雨水浸盆，绝不用自来水",
    careTemp: "5-30°C，冬季 < 10°C 休眠",
    careHumidity: "中高",
    careNotes: "不施肥；偶尔喂活虫即可，频繁触发夹子会衰竭。",
  },
  {
    commonName: "茅膏菜",
    scientificName: "Drosera spp.",
    family: "茅膏菜科",
    category: "食虫",
    careLight: "明亮散光至全日",
    careWater: "纯水浸盆",
    careTemp: "5-30°C",
    careHumidity: "高",
    careNotes: "叶面腺毛黏小虫；忌自来水矿物质。",
  },
  {
    commonName: "瓶子草",
    scientificName: "Sarracenia spp.",
    family: "瓶子草科",
    category: "食虫",
    careLight: "全日照",
    careWater: "纯水浸盆，盆托常存水",
    careTemp: "0-30°C，冬季半休眠",
    careHumidity: "中高",
    careNotes: "高瓶状叶捕虫；需冬季冷凉休眠。",
  },
  {
    commonName: "猪笼草",
    scientificName: "Nepenthes spp.",
    family: "猪笼草科",
    category: "食虫/附生",
    careLight: "明亮散光",
    careWater: "纯水/雨水保持湿润",
    careTemp: "18-30°C",
    careHumidity: "极高",
    careNotes: "瓶内可留少量水；湿度低瓶子退化不长。",
  },

  // —— 仙人掌 ——
  {
    commonName: "金琥",
    scientificName: "Echinocactus grusonii",
    family: "仙人掌科",
    category: "仙人掌",
    careLight: "全日照",
    careWater: "干透浇透，冬季近断水",
    careTemp: "5-35°C",
    careHumidity: "低",
    careNotes: "成株可达盆球；长寿命，几十年慢慢长。",
  },
  {
    commonName: "兔耳",
    scientificName: "Opuntia microdasys",
    family: "仙人掌科",
    category: "仙人掌",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "5-32°C",
    careHumidity: "低",
    careNotes: "刺座细刺易扎人；耐旱省心。",
  },
  {
    commonName: "白桃扇",
    scientificName: "Opuntia microdasys 'Albata'",
    family: "仙人掌科",
    category: "仙人掌",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "5-32°C",
    careHumidity: "低",
    careNotes: "白色细刺品种；同样易扎人，戴手套打理。",
  },

  // —— 草花 ——
  {
    commonName: "三色堇",
    scientificName: "Viola × wittrockiana",
    family: "堇菜科",
    category: "一年生草花",
    careLight: "全日照",
    careWater: "盆土微干就浇",
    careTemp: "5-18°C",
    careHumidity: "中",
    careNotes: "冷凉花卉；> 25°C 易褪色枯萎。",
  },
  {
    commonName: "角堇",
    scientificName: "Viola cornuta",
    family: "堇菜科",
    category: "一年生草花",
    careLight: "全日照",
    careWater: "盆土微干就浇",
    careTemp: "5-20°C",
    careHumidity: "中",
    careNotes: "三色堇近亲，花更小更密；勤摘残花。",
  },
  {
    commonName: "雏菊",
    scientificName: "Bellis perennis",
    family: "菊科",
    category: "一年生草花",
    careLight: "全日照",
    careWater: "盆土微干就浇",
    careTemp: "5-20°C",
    careHumidity: "中",
    careNotes: "冷凉小菊；夏季高温常半枯。",
  },
  {
    commonName: "向日葵",
    scientificName: "Helianthus annuus",
    family: "菊科",
    category: "一年生草花",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "15-30°C",
    careHumidity: "低-中",
    careNotes: "幼苗追光性强；小盆栽用矮型品种。",
  },
  {
    commonName: "洋桔梗",
    scientificName: "Eustoma grandiflorum",
    family: "龙胆科",
    category: "草花",
    careLight: "明亮散光至全日",
    careWater: "盆土微干就浇",
    careTemp: "15-25°C",
    careHumidity: "中",
    careNotes: "瓣型像玫瑰；播种较慢，常买苗。",
  },
  {
    commonName: "勿忘我",
    scientificName: "Myosotis sylvatica",
    family: "紫草科",
    category: "草花",
    careLight: "半阴至明亮散光",
    careWater: "保持湿润",
    careTemp: "10-22°C",
    careHumidity: "中",
    careNotes: "冷凉花卉；蓝色小星花海。",
  },
  {
    commonName: "报春花",
    scientificName: "Primula spp.",
    family: "报春花科",
    category: "多年生草花",
    careLight: "散光",
    careWater: "保持湿润",
    careTemp: "5-20°C",
    careHumidity: "中高",
    careNotes: "冷凉早春开花；夏季高温短日避光休眠。",
  },
];

async function main() {
  await db.insert(species).values(SEED).onConflictDoNothing();
  console.log(`Seeded ${SEED.length} species (existing rows skipped).`);
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
