import { db } from "./index";
import { species } from "./schema";

const SEED: (typeof species.$inferInsert)[] = [
  // 已存在的不会重复（onConflictDoNothing），按 commonName 自然合并
  {
    commonName: "绿萝",
    scientificName: "Epipremnum aureum",
    family: "天南星科",
    category: "观叶",
    careLight: "散光，避免直射",
    careWater: "土干透浇透，约 5-10 天 / 次",
    careTemp: "15-28°C",
    careHumidity: "中高湿度，可叶面喷雾",
    careNotes: "极易繁殖，剪枝水插即可生根。",
  },
  {
    commonName: "多肉·桃蛋",
    scientificName: "Graptopetalum amethystinum",
    family: "景天科",
    category: "多肉",
    careLight: "全日照，弱光易徒长",
    careWater: "干透浇透，秋冬控水",
    careTemp: "5-30°C，怕高温闷",
    careHumidity: "低，需通风",
    careNotes: "夏季避免暴晒+雨淋；冷凉季节出粉上色。",
  },
  {
    commonName: "龟背竹",
    scientificName: "Monstera deliciosa",
    family: "天南星科",
    category: "观叶",
    careLight: "明亮散光",
    careWater: "表土干 2-3cm 再浇，约 7 天 / 次",
    careTemp: "18-30°C",
    careHumidity: "中高湿度，叶面喷雾或加湿器",
    careNotes: "立柱可促叶片开裂；春夏施肥 2-4 周一次。",
  },
  // ↓ 用户补充列表
  {
    commonName: "秋海棠",
    scientificName: "Begonia spp.",
    family: "秋海棠科",
    category: "观叶/观花",
    careLight: "明亮散光，避免烈日",
    careWater: "表土微干就浇，约 4-7 天",
    careTemp: "15-25°C",
    careHumidity: "高湿，怕闷",
    careNotes: "夏季避高温闷热；叶面少喷水易烂。",
  },
  {
    commonName: "矮牵牛",
    scientificName: "Petunia × hybrida",
    family: "茄科",
    category: "一年生草本",
    careLight: "全日照",
    careWater: "盆土发白再浇，约 2-3 天，花期更勤",
    careTemp: "15-28°C",
    careHumidity: "中等",
    careNotes: "花后摘残花，控顶可塑花球；忌淋雨。",
  },
  {
    commonName: "蓝目菊",
    scientificName: "Osteospermum spp.",
    family: "菊科",
    category: "多年生草花",
    careLight: "全日照",
    careWater: "干透浇透，约 3-5 天",
    careTemp: "10-25°C，耐寒不耐酷暑",
    careHumidity: "低-中",
    careNotes: "夏季高温会假死，秋凉恢复；勤摘残花。",
  },
  {
    commonName: "卷叶榕",
    scientificName: "Ficus benjamina 'Curly'",
    family: "桑科",
    category: "木本观叶",
    careLight: "明亮散光",
    careWater: "表土干就浇，约 5-7 天",
    careTemp: "15-28°C",
    careHumidity: "中高",
    careNotes: "怕频繁挪动，换位置后掉叶属正常。",
  },
  {
    commonName: "鸭脚木",
    scientificName: "Heptapleurum arboricola",
    family: "五加科",
    category: "木本观叶",
    careLight: "散光至半阴",
    careWater: "干透浇透，约 7-10 天",
    careTemp: "10-28°C",
    careHumidity: "中",
    careNotes: "净化空气强，养护省心，怕积水。",
  },
  {
    commonName: "飞机蔓绿绒",
    scientificName: "Philodendron 'Florida Beauty'",
    family: "天南星科",
    category: "观叶",
    careLight: "明亮散光",
    careWater: "表土干 2cm 再浇，约 5-7 天",
    careTemp: "18-28°C",
    careHumidity: "中高，多喷雾",
    careNotes: "立柱可促长大叶；气根别剪。",
  },
  {
    commonName: "迷岩",
    scientificName: "Aeonium 'Mardi Gras'",
    family: "景天科",
    category: "多肉",
    careLight: "全日照",
    careWater: "干透浇透，夏季控水",
    careTemp: "5-25°C",
    careHumidity: "低，强通风",
    careNotes: "夏季可能休眠掉叶；秋凉重新生长。",
  },
  {
    commonName: "迷套",
    scientificName: "Sedum spp.",
    family: "景天科",
    category: "多肉",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "5-30°C",
    careHumidity: "低",
    careNotes: "极易繁殖，叶插成功率高。",
  },
  {
    commonName: "花猫",
    scientificName: "Echeveria 'Catorce'",
    family: "景天科",
    category: "多肉",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "5-28°C",
    careHumidity: "低",
    careNotes: "锦化品种，光照足时叶缘粉红更明显。",
  },
  {
    commonName: "大岩桐",
    scientificName: "Sinningia speciosa",
    family: "苦苣苔科",
    category: "球根",
    careLight: "明亮散光",
    careWater: "表土微干浇水，避免叶面",
    careTemp: "18-25°C",
    careHumidity: "中高",
    careNotes: "花后块茎休眠，冬季可断水保块茎。",
  },
  {
    commonName: "堇兰",
    scientificName: "Miltoniopsis spp.",
    family: "兰科",
    category: "兰花",
    careLight: "明亮散光",
    careWater: "介质微干浇透，怕积水",
    careTemp: "15-25°C",
    careHumidity: "高",
    careNotes: "花型像三色堇；空气流通很关键。",
  },
  {
    commonName: "皮草花",
    scientificName: "Episcia cupreata",
    family: "苦苣苔科",
    category: "观叶/观花",
    careLight: "明亮散光",
    careWater: "表土微干就浇",
    careTemp: "18-28°C",
    careHumidity: "高",
    careNotes: "叶子绒毛，怕碰水；用浸盆法。",
  },
  {
    commonName: "文心兰",
    scientificName: "Oncidium spp.",
    family: "兰科",
    category: "兰花",
    careLight: "明亮散光",
    careWater: "假鳞茎微皱再浇",
    careTemp: "15-28°C",
    careHumidity: "中高",
    careNotes: "花后剪掉花梗保留假鳞茎；周年可发芽。",
  },
  {
    commonName: "迷迭香",
    scientificName: "Salvia rosmarinus",
    family: "唇形科",
    category: "香草",
    careLight: "全日照",
    careWater: "干透浇透，怕涝",
    careTemp: "5-30°C",
    careHumidity: "低",
    careNotes: "耐旱不耐湿；多通风，少氮肥。",
  },
  {
    commonName: "薄荷",
    scientificName: "Mentha spp.",
    family: "唇形科",
    category: "香草",
    careLight: "全日照至半阴",
    careWater: "表土发干就浇，约 2-3 天",
    careTemp: "10-28°C",
    careHumidity: "中",
    careNotes: "生命力强，繁殖快；建议单独一盆防「抢地盘」。",
  },
  {
    commonName: "长寿花",
    scientificName: "Kalanchoe blossfeldiana",
    family: "景天科",
    category: "多肉/观花",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "10-25°C",
    careHumidity: "低",
    careNotes: "短日照诱导花芽（每天 < 10h 光照 6-8 周）。",
  },
  {
    commonName: "百万小铃",
    scientificName: "Calibrachoa spp.",
    family: "茄科",
    category: "草花",
    careLight: "全日照",
    careWater: "表土干就浇，花期勤浇",
    careTemp: "10-28°C",
    careHumidity: "中",
    careNotes: "花后摘残花促复花；夏季避烈日。",
  },
  {
    commonName: "百日草",
    scientificName: "Zinnia elegans",
    family: "菊科",
    category: "一年生草花",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "15-30°C",
    careHumidity: "中",
    careNotes: "极易播种，30 天发芽到开花约 60 天。",
  },
  {
    commonName: "翠芦莉",
    scientificName: "Ruellia simplex",
    family: "爵床科",
    category: "草花",
    careLight: "全日照",
    careWater: "盆土微干就浇",
    careTemp: "15-30°C",
    careHumidity: "中高",
    careNotes: "一日花，每天开新花；可粗放养护。",
  },
  {
    commonName: "紫叶酢浆草",
    scientificName: "Oxalis triangularis",
    family: "酢浆草科",
    category: "球根",
    careLight: "散光",
    careWater: "盆土微干浇水",
    careTemp: "15-25°C",
    careHumidity: "中",
    careNotes: "夜间叶子合拢；夏季会暂时休眠。",
  },
  {
    commonName: "虎刺梅",
    scientificName: "Euphorbia milii",
    family: "大戟科",
    category: "多肉/观花",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "15-30°C",
    careHumidity: "低",
    careNotes: "汁液有毒勿入眼；浇水耐寒不如耐旱。",
  },
  {
    commonName: "绣球花",
    scientificName: "Hydrangea macrophylla",
    family: "绣球科",
    category: "灌木/观花",
    careLight: "明亮散光至半阴",
    careWater: "盆土稍干就浇，花期大水",
    careTemp: "10-25°C",
    careHumidity: "中高",
    careNotes: "土壤 pH 影响花色：酸蓝碱粉。冬季注意修剪老枝。",
  },
  {
    commonName: "龙鳞春雨",
    scientificName: "Philodendron 'Dragon Scale'",
    family: "天南星科",
    category: "观叶",
    careLight: "明亮散光",
    careWater: "表土干 2cm 再浇",
    careTemp: "18-28°C",
    careHumidity: "高",
    careNotes: "叶面有龙鳞质感，喜湿；立柱可长更大叶。",
  },
  {
    commonName: "野路菊",
    scientificName: "Rhodanthemum hosmariense",
    family: "菊科",
    category: "多年生草花",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "5-25°C",
    careHumidity: "低",
    careNotes: "耐寒小菊；花期长，避免淋雨烂根。",
  },
  {
    commonName: "纸鳞托菊",
    scientificName: "Rhodanthe spp.",
    family: "菊科",
    category: "一年生草花",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "10-25°C",
    careHumidity: "低",
    careNotes: "纸质花瓣，干燥后亦能做干花。",
  },
  {
    commonName: "摩洛哥雏菊",
    scientificName: "Rhodanthemum hosmariense 'Casablanca'",
    family: "菊科",
    category: "多年生草花",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "5-25°C",
    careHumidity: "低",
    careNotes: "灰绿叶+白瓣黄心；忌闷湿。",
  },
  {
    commonName: "铁线莲",
    scientificName: "Clematis spp.",
    family: "毛茛科",
    category: "攀援藤本",
    careLight: "上部全日照，根部阴凉",
    careWater: "盆土稍干就浇",
    careTemp: "5-28°C",
    careHumidity: "中",
    careNotes: "三大修剪组：第一组只剪枯，二组花后轻剪，三组重剪；上盆给棚架。",
  },
  {
    commonName: "旱金莲",
    scientificName: "Tropaeolum majus",
    family: "旱金莲科",
    category: "草花/食用",
    careLight: "全日照",
    careWater: "干透浇透",
    careTemp: "10-28°C",
    careHumidity: "中",
    careNotes: "花和叶可食用，味微辣；不喜大水大肥。",
  },
  {
    commonName: "美女樱",
    scientificName: "Verbena × hybrida",
    family: "马鞭草科",
    category: "草花",
    careLight: "全日照",
    careWater: "盆土微干就浇",
    careTemp: "10-28°C",
    careHumidity: "中",
    careNotes: "丰花连续开，花后剪一刀促复花。",
  },
  {
    commonName: "露薇花",
    scientificName: "Lewisia cotyledon",
    family: "马齿苋科",
    category: "多年生草花",
    careLight: "散光至明亮",
    careWater: "干透浇透，怕涝",
    careTemp: "5-22°C",
    careHumidity: "低",
    careNotes: "原产高山，要求排水极佳；铺面石防领口烂。",
  },
  {
    commonName: "玲珑菊",
    scientificName: "Argyranthemum frutescens",
    family: "菊科",
    category: "灌木状草花",
    careLight: "全日照",
    careWater: "盆土微干就浇",
    careTemp: "5-25°C",
    careHumidity: "中",
    careNotes: "可塑棒棒糖造型；夏季避酷暑。",
  },
];

async function main() {
  await db.insert(species).values(SEED).onConflictDoNothing();
  console.log(`Seeded ${SEED.length} species (existing rows skipped).`);
}

main()
  .then(() => process.exit(0))
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
